<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYixy7ej\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYixy7ej/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYixy7ej.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYixy7ej\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYixy7ej\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yixy7ej',
    'container.build_id' => '9a9af350',
    'container.build_time' => 1700573828,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYixy7ej');
