<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUS0VC1g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUS0VC1g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUS0VC1g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUS0VC1g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUS0VC1g\App_KernelDevDebugContainer([
    'container.build_hash' => 'US0VC1g',
    'container.build_id' => 'ae90bc87',
    'container.build_time' => 1700222068,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUS0VC1g');
