<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYB6b1BE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYB6b1BE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYB6b1BE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYB6b1BE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYB6b1BE\App_KernelDevDebugContainer([
    'container.build_hash' => 'YB6b1BE',
    'container.build_id' => '7e9b75fe',
    'container.build_time' => 1700834586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYB6b1BE');
