<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.ec2b70cf.js',
                '/build/app.aa1bf742.js',
            ],
            'css' => [
                '/build/app.f8c4e978.css',
            ],
        ],
        'register' => [
            'js' => [
                '/build/runtime.ec2b70cf.js',
                '/build/register.6c1c31d7.js',
            ],
            'css' => [
                '/build/register.7b0d0770.css',
            ],
        ],
        'login' => [
            'js' => [
                '/build/runtime.ec2b70cf.js',
                '/build/login.4f1de672.js',
            ],
            'css' => [
                '/build/login.7b0d0770.css',
            ],
        ],
        'daily' => [
            'js' => [
                '/build/runtime.ec2b70cf.js',
                '/build/43.cb125481.js',
                '/build/daily.0a517518.js',
            ],
            'css' => [
                '/build/daily.bd4c71b0.css',
            ],
        ],
        'profile' => [
            'js' => [
                '/build/runtime.ec2b70cf.js',
                '/build/profile.62e65466.js',
            ],
            'css' => [
                '/build/profile.802c33d2.css',
            ],
        ],
    ],
],

]];
