<?php

namespace ContainerHwEUZKM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IFAVO0eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iFAVO0e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iFAVO0e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'session' => ['privates', '.errored..lXIVvF', NULL, 'Cannot determine controller argument for "App\\Controller\\EditController::delete()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\SessionInterface". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'session' => '?',
        ]);
    }
}
